--- @class Buffer
--- @field fillUint8 fun(self: Buffer, value: number)
--- @field setFloat32 fun(self: Buffer, offset: number, value: number)
--- @class buffer
--- @field alloc fun(sizeOfBytes: number): Buffer
--- @field fromString fun(s: string): Buffer