name: Build With MSVC
on: [push]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run CMake (Configure)
        run: cmake -S packages/hello_embree_host -B packages/hello_embree_host/build -A x64 -DCMAKE_BUILD_TYPE=Release
      - name: Run CMake (Build)
        run: cmake --build packages/hello_embree_host/build --config Release --parallel
      - name: Run (CTest)
        run: ctest --test-dir packages/hello_embree_host/build -C Release